name:                test-dsl
version:             0.1.0.0
github:              "githubuser/test-dsl"
license:             BSD3
author:              "John A. De Goes"
maintainer:          "john@degoes.net"
copyright:           "2018 John A. De Goes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/test-dsl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  test-dsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-dsl

tests:
  test-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-dsl
